### ISSUE TITLE
Enter Sky Peak Without 1st Station Pass

### ISSUE THREAD

**Issue by savan9939** [CrypticMonkey33/ArchipelagoExplorersOfSky#119]
### What happened?

Driftblim's Gondola will take me to the 2nd, 4th and 6th Station clearing to let me enter Sky Peak from Shaymin village, but the 1st Station Path (nor any station pass after) have been unlocked. When attempting to enter Sky Peak directly from Shaymin Village, it tells me it is locked, as intended.

### What were the expected results?

Driftblim should not let me enter clearings I have not unlocked or reached.

**Comment by HappyLappy1** [comment]
This has been tentatively fixed in 0.3.0. I'd like to verify that Driftblim works as expected though. Here's what needs to be tested:
- With just Shaymin Village, Driftblim doesn't allow access to any station clearing. 
- With access to 2nd Station **Clearing** (2nd and 3rd station pass), Driftblim can take you there from the village
- Same for all other stations with a gondola.

**Comment by FieryBlizzard** [comment]
As of the current bsdiff and apworld, drifblim still appears in shaymin village with zero items and lets you go to the 2nd, 4th, and 6th clearing. You can then proceed to the next clearing without any sky peak progression items.

**Comment by HappyLappy1** [comment]
Tentatively fixed!

**Comment by CrypticMonkey33** [comment]
0.3.0 rc out now
